# database模块配置文件
# 模块名称: database
# 包名: database  
# 描述: 数据库模块
# 生成时间: 2025-11-27 01:06:01
# 注意: 此文件由配置生成器自动生成

# type配置
type: mysql
# enabled配置
enabled: true
# default配置
default: mysql
# my sql配置
mysql:
    module_name: mysql
    host: localhost
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    log-level: info
    db-name: test
    username: root
    password: mysql_password
    max-idle-conns: 10
    max-open-conns: 100
    conn-max-idle-time: 300
    conn-max-life-time: 3600
# postgre sql配置
postgresql:
    module_name: postgresql
    host: localhost
    port: "5432"
    config: sslmode=disable
    log-level: info
    db-name: postgres
    username: postgres
    password: postgres_password
    max-idle-conns: 10
    max-open-conns: 100
    conn-max-idle-time: 300
    conn-max-life-time: 3600
# sqlite配置
sqlite:
    module_name: sqlite
    config: _foreign_keys=on
    log-level: info
    db-path: ./data.db
    vacuum: false
    max-idle-conns: 10
    max-open-conns: 1
    conn-max-idle-time: 300
    conn-max-life-time: 3600
