# wsc模块配置文件
# 模块名称: wsc
# 包名: wsc  
# 描述: WebSocket通信模块
# 生成时间: 2025-11-28 00:26:09
# 注意: 此文件由配置生成器自动生成

# 是否启用
enabled: false
# 节点IP
node-ip: 0.0.0.0
# 节点端口
node-port: 8080
# 心跳间隔(秒)
heartbeat-interval: 30
# 客户端超时(秒)
client-timeout: 90
# 消息缓冲区大小
message-buffer-size: 256
# 允许的WebSocket Origin
websocket-origins:
    - '*'
# 读取超时(秒)
read-timeout: 10s
# 写入超时(秒)
write-timeout: 10s
# 空闲超时(秒)
idle-timeout: 2m0s
# 最大消息长度
max-message-size: 512
# 最小重连时间
min-rec-time: 2s
# 最大重连时间
max-rec-time: 1m0s
# 重连因子
rec-factor: 1.5
# 是否自动重连
auto-reconnect: true
# 最大重试次数
max-retries: 3
# 基本重试延迟
base-delay: 100ms
# 最大重试延迟
max-delay: 5s
# 消息确认超时(毫秒)
ack-timeout-ms: 500ms
# 消息确认最大重试次数
ack-max-retries: 3
# 是否启用消息确认
enable-ack: false
# 重试延迟倍数
backoff-factor: 2
# 是否添加随机抖动
jitter: true
# 可重试的错误类型
retryable-errors:
    - queue_full
    - timeout
    - conn_error
    - channel_closed
# 不可重试的错误类型
non-retryable-errors:
    - user_offline
    - permission
    - validation
# 是否启用熔断器
enable-circuit-breaker: false
# SSE心跳间隔(秒)
sse-heartbeat: 0
# SSE超时(秒)
sse-timeout: 120
# SSE消息缓冲区大小
sse-message-buffer: 100
# 分布式配置
distributed:
    # 是否启用
    enabled: false
    node-discovery: redis
    node-sync-interval: 30
    message-routing: hash
    enable-load-balance: true
    health-check-interval: 10
    node-timeout: 60
    cluster-name: wsc-cluster
# 群组配置
group:
    # 是否启用
    enabled: false
    max-group-size: 500
    max-groups-per-user: 100
    enable-broadcast: true
    broadcast-rate-limit: 10
    group-cache-expire: 3600
    auto-create-group: false
    enable-message-record: true
# 性能配置
performance:
    max-connections-per-node: 10000
    read-buffer-size: 4
    write-buffer-size: 4
    enable-compression: false
    compression-level: 6
    enable-metrics: true
    metrics-interval: 60
    enable-slow-log: true
    slow-log-threshold: 1000
# 安全配置
security:
    enable-auth: true
    enable-encryption: false
    enable-rate-limit: true
    # 最大消息长度
    max-message-size: 1024
    allowed-user-types:
        - customer
        - agent
        - admin
    blocked-ips: []
    whitelist-ips: []
    enable-ip-whitelist: false
    token-expiration: 3600
    max-login-attempts: 5
    login-lock-duration: 300
# 增强功能配置
enhancement:
    # 是否启用
    enabled: false
    smart-routing: true
    load-balancing: true
    smart-queue: true
    monitoring: true
    cluster-management: false
    rule-engine: true
    circuit-breaker: true
    message-filtering: true
    performance-tracking: true
    advanced-metrics: false
    alert-system: true
    failure-threshold: 5
    success-threshold: 3
    circuit-timeout: 30
    max-queue-size: 1000
    metrics-interval: 60
    max-samples: 1000
    load-balance-algorithm: round-robin
# 数据库名称 (嵌套配置对象)
database:
    # 是否启用
    enabled: true
    auto-migrate: true
    table-prefix: wsc_
    log-level: warn
    slow-threshold: 200ms
# 队列配置
queue:
    # 是否启用
    enabled: false
    type: redis
    batch-size: 10
    # 最大重试次数
    max-retries: 3
    retry-interval: 5s
    process-timeout: 30s
    prefetch-count: 1
    dead-letter-ttl: 24h0m0s
    priority: true
    persistent: true
# 定时任务配置
jobs:
    # 是否启用
    enabled: false
    tasks:
        cleanup:
            # 是否启用
            enabled: true
            cron: ""
            interval: 5m0s
            timeout: 1m0s
            # 最大重试次数
            max-retries: 3
            description: 清理过期连接和数据
            concurrency: 1
            skip-if-running: true
            params: {}
        message-archive:
            # 是否启用
            enabled: true
            cron: 0 0 2 * * *
            interval: 0s
            timeout: 30m0s
            # 最大重试次数
            max-retries: 3
            description: 归档旧消息（3天前归档，60天后删除）
            concurrency: 1
            skip-if-running: true
            params: {}
        offline-message:
            # 是否启用
            enabled: true
            cron: ""
            interval: 1m0s
            timeout: 30s
            # 最大重试次数
            max-retries: 3
            description: 推送离线消息
            concurrency: 1
            skip-if-running: true
            params: {}
        queue-process:
            # 是否启用
            enabled: true
            cron: ""
            interval: 10s
            timeout: 30s
            # 最大重试次数
            max-retries: 5
            description: 处理队列任务
            concurrency: 2
            skip-if-running: true
            params: {}
        stats-collect:
            # 是否启用
            enabled: true
            cron: 0 */5 * * * *
            interval: 0s
            timeout: 1m0s
            # 最大重试次数
            max-retries: 3
            description: 收集统计数据
            concurrency: 1
            skip-if-running: true
            params: {}
        status-sync:
            # 是否启用
            enabled: true
            cron: ""
            interval: 30s
            timeout: 15s
            # 最大重试次数
            max-retries: 3
            description: 同步用户在线状态
            concurrency: 1
            skip-if-running: true
            params: {}
# 日志配置
logging:
    module-name: wsc
    # 是否启用
    enabled: true
    level: info
    format: json
    output: stdout
    file-path: /var/log/wsc.log
    max-size: 100
    max-backups: 3
    max-age: 28
    compress: true
    skip-paths:
        - /health
        - /metrics
    enable-request: true
    enable-response: false
