# logging模块配置文件
# 模块名称: logging
# 包名: logging  
# 描述: 日志记录模块
# 生成时间: 2025-11-28 00:26:08
# 注意: 此文件由配置生成器自动生成

# 模块名称
module-name: logging
# 是否启用日志
enabled: true
# 日志级别
level: info
# 日志格式 (json, text)
format: json
# 输出目标 (stdout, file)
output: stdout
# 日志文件路径
file-path: /var/log/app.log
# 最大文件大小(MB)
max-size: 100
# 最大备份文件数
max-backups: 3
# 最大保存天数
max-age: 28
# 是否压缩
compress: true
# 跳过的路径
skip-paths:
    - /health
    - /metrics
# 是否记录请求
enable-request: true
# 是否记录响应
enable-response: false
